### PR TITLE
Review EM_* message correctness

### LINKED ISSUE #994: TextBox and MaskedTextBox.GetPositionFromCharIndex() and MaskedTextBox.GetCharIndexFromPosition() methods return the incorrect values
* Have you experienced this same bug with .NET Framework?: No

**OS:** RS4 X64
**VS:** Dev16 16.2.0 Preview 1.0 [28913.52.d16.2]
**.NET Core:** 3.0.100-preview6-011867 from Master branch

**More Info:**
This issue can repro in TextBox control too, but RichTextBox control works well. 

**Steps to reproduce:**
1.	Install the .NET Core 3.0 SDK from https://github.com/dotnet/core-sdk for Master branch.
2.	Open the attached ‘.NETCoreTestcase’ .NET Core app in VS.
3.	Start it and observe the returned values from GetPositionFromCharIndex() and GetCharIndexFromPosition() methods in debugging result.
[NETCoreTestcase.zip](https://github.com/dotnet/winforms/files/3181261/NETCoreTestcase.zip)

**Actual:** 
Both of the returned values are 0. 
NETCoreResult1

**Expected:** 
These two methods should return the correct values, like it works in .NET Framework. 
NETFrameworkResult1

### PR DESCRIPTION
**Pull request by RussKie**
## Proposed changes

- As part the #791 refactor `EM_*` messages got mixed with `RTB.EM_*` messages that led to an issue described in #994.

  * Restore correct EM_ messagest
  * Separate RTB.EM_ messages
  * Update RichTextBox to use RTB.EM_* messages

Fixes #994

### CODE REVIEW

**Comment by hughbe** [comment]
I'm so sorry you had to do this!

**Comment by RussKie** [comment]
Apologies accepted 🤝 😃 

It would be great if you could strive for smaller and targeted PRs in the future.

**Comment by weltkante** [comment]
wow, its really unfortunate that the windows header files `#define` the same macro name with two different values! (`richedit.h` vs. `winuser.h`)

You might want to add some comments to the definition class to make sure these mistakes are not repeated

**Comment by RussKie** [comment]
> You might want to add some comments to the definition class to make sure these mistakes are not repeated

Please feel free to add comments where you feel appropriate.

**Comment by weltkante** [comment]
@RussKie sorry having to ask, but how do you want me to do that? Comment on the PR with the "suggested change" function? Separate PR after this is merged? Some other way to add changes to a not-yet-merged PR I don't know of?

**Comment by RussKie** [comment]
> Comment on the PR with the "suggested change"

That will work.

Everyone is welcome to review and comment on all submissions.

**Comment by RussKie** [comment]
@Olina-Zhang I've run the same code as provided in #994 and it appears to be working:
image

The different value is probably different due to the default font change (https://github.com/dotnet/winforms/pull/656).

File: src/Common/src/Interop/Interop.RichEditMessages.cs [hunk 1]
```diff
@@ -0,0 +1,116 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+internal static partial class Interop
+{
+    public static class RichEditMessages
+    {
+        public const int EM_GETLIMITTEXT = (WindowMessages.WM_USER + 37);
```
Comment (JeremyKuhne) [inline src/Common/src/Interop/Interop.RichEditMessages.cs]: These first four `EM_GETLIMITTEXT` , `EM_POSFROMCHAR`, `EM_CHARFROMPOS`, and `EM_SCROLLCARET` are a little odd. The "normal" definitions should work with the RichEdit control from what the headers/docs seem to indicate. It may be safer and less confusing to remove them.

Comment (RussKie) [reply src/Common/src/Interop/Interop.RichEditMessages.cs]: 🤔  These existed in the original definition:
image

Their values (as defined in `richedit.h`) are different from those defined in `winuser.h` (thanks @weltkante for the pointers). Though looking at the definitions in `richedit.h` the messages are conditionally defined:
```cpp
#ifndef EM_GETLIMITTEXT
#define EM_GETLIMITTEXT 		(WM_USER + 37)
#endif

#ifndef EM_POSFROMCHAR	
#define EM_POSFROMCHAR			(WM_USER + 38)
#define EM_CHARFROMPOS			(WM_USER + 39)
#endif

#ifndef EM_SCROLLCARET
#define EM_SCROLLCARET			(WM_USER + 49)
#endif
```

Do you think it is safe to remove these four messages?
How can we test (I'm outside my depth here)?

**Comment by Olina-Zhang** [comment]
@RussKie, we will verify issue [#994 ](https://github.com/dotnet/winforms/issues/994) when fixed .net core build is ready.

File: src/Common/src/Interop/Interop.RichEditMessages.cs (hunk 1 above)
Comment (weltkante) [reply src/Common/src/Interop/Interop.RichEditMessages.cs]: The `#ifndef` is probably just there to suppress macro redefinition warnings. Depending on which version is imported first the RTF messages may be visible to C/C++ code. However I don't know if its even possible to import `richedit.h` without `winuser.h` - when I try to import `richedit.h` as the only header VS intellisense still says its using the version from `winuser.h` - so it may be the case that those particular conflicting messages never actually are used in C/C++ code. In this case it would be safe to remove I think.

I'll have another look and try to verify the `#include` order to make sure whether it is possible to use the RTF version at all in C/C++

Comment (weltkante) [reply src/Common/src/Interop/Interop.RichEditMessages.cs]: I can verify that its impossible to include `richedit.h` before `winuser.h` in the windows 10 headers because richedit.h includes winuser.h indirectly.

```
1>------ Rebuild All started: Project: TestProject, Configuration: Debug Win32 ------
1>test.cpp
1>Note: including file: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\Richedit.h
1>Note: including file:  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared\wtypes.h
1>Note: including file:   c:\program files (x86)\windows kits\10\include\10.0.17763.0\shared\rpc.h
1>Note: including file:    C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\windows.h
1>Note: including file:     C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\winuser.h
```

Therefore C/C++ code will never see the RPC-specific conflicting messages due to the `#ifndef` never being true.

I think its safe to drop these constants from WinForms if native code never can use them.

File: src/Common/src/Interop/Interop.RichEditMessages.cs [hunk 2]
```diff
@@ -0,0 +1,116 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+internal static partial class Interop
+{
+    public static class RichEditMessages
```
Comment (weltkante) [inline src/Common/src/Interop/Interop.RichEditMessages.cs]: Might want to add a warning/comment here. If the conflicting messages are removed like @JeremyKuhne suggested this is probably not necessary though.

```suggestion
    /// <summary>RichTextBox specific window messages. Note that some messages have the same name but different value compared to normal TextBox messages.</summary>
    public static class RichEditMessages
```

File: src/Common/src/Interop/Interop.RichEditMessages.cs (hunk 1 above)
Comment (RussKie) [reply src/Common/src/Interop/Interop.RichEditMessages.cs]: Awesome, thanks heaps for the investigation!

File: src/Common/src/Interop/Interop.RichEditMessages.cs [hunk 3]
```diff
@@ -0,0 +1,114 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+internal static partial class Interop
+{
+    /// <summary>
+    /// RichTextBox Control Messages. Note that some messages have the same name but different value compared to normal Edit Control Messages.
```
Comment (JeremyKuhne) [inline src/Common/src/Interop/Interop.RichEditMessages.cs]: Nit: the second part of the comment isn't relevant now that you've removed the dupes. :)

Comment (RussKie) [reply src/Common/src/Interop/Interop.RichEditMessages.cs]: I think it is still relevant, since there dups in richedit.h; if someone decides to copy them they may be (more) aware.
