### PR TITLE
fix issue #13648  DemoConsole app: The extra number displayed on Name & Text Propeties for the ToolStrip control

### LINKED ISSUE #13648: DemoConsole app: The extra number displayed on Name & Text Propeties for the ToolStrip control
### .NET version

The latest main branch of Winforms repo

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

This is a regression issue, can reproduce on release/10.0-preview6 branch, cannot reproduce on release/10.0-preview5 branch

### Issue description

The extra number displayed on Name & Text Propeties for the ToolStrip control

**main branch:**
Image

**release/10.0-preview5** 
Image

**net481**

Image

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) bases on main branch in Winforms repo.

### PR DESCRIPTION
**Pull request by Epica3055**
Fixes #13648  

## Proposed changes

- 
- We need to match the exact type name shouldn't just use StartsWith since we removed type check in [pr13573](https://github.com/dotnet/winforms/pull/13573)
- 

```diff
        while (i < cc.Count)
        {
-            if (cc[i] is Component comp && comp.GetType() == type)
+            if (cc[i] is Component comp)
             {
                string name = comp.Site.Name;
                if (name.StartsWith(type.Name, StringComparison.Ordinal))


```

### Before

image

### After

image

## Test methodology 

- 
- manual 
- 

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/winforms/pull/13650)

### CODE REVIEW

File: src/test/integration/DesignSurface/DesignSurfaceExt/NameCreationServiceImp.cs [hunk 1]
```diff
@@ -31,13 +31,22 @@ public string CreateName(IContainer container, Type type)
             if (cc[i] is Component comp)
             {
                 string name = comp.Site.Name;
-                if (name.StartsWith(type.Name, StringComparison.Ordinal))
+                int numberStartIndex = name.Length - 1;
```
Comment (LeafShi1) [inline src/test/integration/DesignSurface/DesignSurfaceExt/NameCreationServiceImp.cs]: Should we consider the following situation:

1. If the component name is `Button` (without a numeric suffix)
2. The component name is `ButtonSpecial1`, typeName will be `ButtonSpecial`, and type.Name will be `Button`, so the judgment will fail.

How about modifying it like this?
```
if (name.StartsWith(type.Name, StringComparison.Ordinal))
{
    string suffix = name[type.Name.Length..];
    if (!string.IsNullOrEmpty(suffix) && suffix.All(char.IsDigit))
    {
        count++;
        try
        {
            int value = int.Parse(suffix);
            if (value < min)
                min = value;
            if (value > max)
                max = value;
        }
        catch (Exception) { }
    }
```

**Review by LeafShi1 — APPROVED** [review]
