### PR TITLE
Fix Interop.User32.PostMessageW return type

### LINKED ISSUE #1981: Interop.User32.PostMessageW has wrong return type
* .NET Core Version: `master` (7019e1414309d820bc377e987cd1efcf9c17a12d)
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
Hi, while adjusting the task dialog code in #1133 for recent interop changes and changing the usage of `UnsafeNativeMethods.PostMessage()` to `Interop.User32.PostMessageW()` (introduced with #1764), I noticed it has a return type of `IntPtr` (meaning 4 byte on 32-bit and 8 byte on 64-bit):
https://github.com/dotnet/winforms/blob/7019e1414309d820bc377e987cd1efcf9c17a12d/src/Common/src/Interop/User32/Interop.PostMessageW.cs#L13-L18

However, `PostMessageW` is defined in `WinUser.h` to return a `BOOL`, which is a C `int` (4 byte on Windows):
```cpp
WINUSERAPI
BOOL
WINAPI
PostMessageW(
    _In_opt_ HWND hWnd,
    _In_ UINT Msg,
    _In_ WPARAM wParam,
    _In_ LPARAM lParam);
```

Therefore, I think using `IntPtr` as return type is not correct, as it could lead to too many bytes being read. Instead, it should be e.g. a `bool` (marshalled as the 4-byte `BOOL`), `Interop.BOOL` or `int`.

**Actual behavior:** 
```c#
public static extern IntPtr PostMessageW(...)
```

**Expected behavior:**
```c#
public static extern bool PostMessageW(...);
// or
public static extern Interop.BOOL PostMessageW(...);
```

Thank you!

### PR DESCRIPTION
**Pull request by gpetrou**
Fixes #1981

## Proposed changes

- Change PostMessageW return type from IntPtr to Interop.BOOL. It seems the return value is not currently used in NativeWindow.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/2204)

### CODE REVIEW

File: src/Common/src/Interop/User32/Interop.PostMessageW.cs [hunk 1]
```diff
@@ -11,19 +11,19 @@ internal static partial class Interop
     internal static partial class User32
     {
         [DllImport(Libraries.User32, ExactSpelling = true)]
-        public static extern IntPtr PostMessageW(
+        public static extern Interop.BOOL PostMessageW(
```
Comment (zsd4yr) [inline src/Common/src/Interop/User32/Interop.PostMessageW.cs]: This looks correct to me.

@JeremyKuhne I believe you touched this code last so you should take a look as well!

Comment (hughbe) [reply src/Common/src/Interop/User32/Interop.PostMessageW.cs]: Can remove Interop namespacing

Comment (gpetrou) [reply src/Common/src/Interop/User32/Interop.PostMessageW.cs]: Sure.
