### PR TITLE
fix: ContextMenuStrip leads to crash on W10 1607

### LINKED ISSUE #2969: DPIAwareness: ArgumentException when opening a ContextMenuStrip
* .NET Core Version: 3.1.0

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

We are experiencing the following crashreports from some users when they open a contextMenu. All reports originate from Windows10 (version 1607 - build 14393 or later), but we are not able to simulate it on our side.

```
System.Windows.Forms.System.ArgumentException: dpiContext (Parameter 'DPI_AWARENESS_CONTEXT_UNSPECIFIED')
    at System.Windows.Forms.CommonUnsafeNativeMethods.TrySetThreadDpiAwarenessContext
    at System.Windows.Forms.DpiHelper+DpiAwarenessScope.Dispose
    at System.Windows.Forms.ToolStripManager+ModalMenuFilter.PreFilterMessage
    at System.Windows.Forms.Application+ThreadContext.ProcessFilters
    at System.Windows.Forms.Application+ThreadContext.PreTranslateMessage
    at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage
    at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop
    at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner
    at System.Windows.Forms.Application+ThreadContext.RunMessageLoop
    at System.Windows.Forms.Application.Run
```

our app is PerMonitorV2 aware as defined in app.manifest:

```
  <asmv3:application>
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
	<dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>
	<dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2, PerMonitor</dpiAwareness>
    </asmv3:windowsSettings>
  </asmv3:application>
```

### PR DESCRIPTION
**Pull request by RussKie**
Resolves #2969.

## Proposed changes

W10 1607 is not fully compatible with PerMonv2, and this leads to crashes interacting with `ContextMenuStrip`.

`CommonUnsafeNativeMethods.SetThreadDpiAwarenessContext` may return `DPI_AWARENESS_CONTEXT_UNSPECIFIED` result that is never checked, however we set `dpiAwarenessScopeIsSet` flag assuming the scope was set.

When disposing the scope we pass the obtained context to `TrySetThreadDpiAwarenessContext` that tries to restore the scope back to the original. However in event the original was `DPI_AWARENESS_CONTEXT_UNSPECIFIED` it leads to ANE, that was observed in #2969.

## Customer Impact

- Customers on W10 1607 will now be able to use `ContextMenuStrip` in `HighDpiMode.PerMonitorV2`
- 

## Regression? 

- Yes

## Risk

- Minimal

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3279)

### CODE REVIEW

**Comment by filipnavara** [comment]
There's wrong issue number in the comment.

**Comment by RussKie** [comment]
> There's wrong issue number in the comment, should be #2969.

🤦‍♂️ Thank you

File: src/Common/src/DpiHelper.DpiAwarenessContext.cs [hunk 1]
```diff
@@ -62,7 +62,7 @@ public DpiAwarenessScope(DpiAwarenessContext awareness)
                             !CommonUnsafeNativeMethods.TryFindDpiAwarenessContextsEqual(originalAwareness, DpiAwarenessContext.DPI_AWARENESS_CONTEXT_UNAWARE))
                         {
                             originalAwareness = CommonUnsafeNativeMethods.SetThreadDpiAwarenessContext(awareness);
-                            dpiAwarenessScopeIsSet = true;
+                            dpiAwarenessScopeIsSet = originalAwareness != DpiAwarenessContext.DPI_AWARENESS_CONTEXT_UNSPECIFIED;
```
Comment (JeremyKuhne) [inline src/Common/src/DpiHelper.DpiAwarenessContext.cs:65]: This is really obfuscated from the docs due to our invented define. Took me 15 minutes to validate what was going on here. To be clearer we should do something like `originalAwareness != 0` and add a comment `\\ Failure to set context is returned as 0 (NULL)`.

**Comment by RussKie** [comment]
The fix is based purely on the reported stack trace. However discussing it with @dreddy-work we couldn't quite work out how it could happen for the reported OS version. 
Standing by for verifications from @dreddy-work.

**Comment by filipnavara** [comment]
I can still reproduce the issue locally so if there is something I can test I will be happy to do so. I'll try to build this PR later to see if it resolves the issue.

**Comment by dreddy-work** [comment]
This fix is safe. Stack trace shows the code that logically should not happen. We tried to repro with same OS and dotnet versions but couldn't repro it. However, customer has a binary ( but not source code) that is resulting in this state.  In either case, this change safe and is good to go.

My guess for repro scenario is, application has manifest file with DPI awareness set to (?) and winforms does not read it from the manifest when creating or setting the windows DPI but has methods calls like GetThreadDPiAwareness() etc.  Somewhere along these, we are in this state.

File: src/Common/src/DpiHelper.DpiAwarenessContext.cs (hunk 1 above)
Comment (dreddy-work) [reply src/Common/src/DpiHelper.DpiAwarenessContext.cs:65]: We defined this constant thinking, it will be easy to read the source code but I agree that this is misleading. This constant is used in other parts of the critical code. Should we take cleaning that up as a separate PR?

**Comment by dreddy-work** [comment]
Also, @filipnavara this PR may fix your issue but we still do not have the root cause for this. Can you share your binary one more time? (earlier link expired and my downloaded documents were cleared). Wanted to inspect binary with tools like Ilspy to get an idea.

**Comment by filipnavara** [comment]
> Also, @filipnavara this PR may fix your issue but we still do not have the root cause for this. Can you share your binary one more time? (earlier link expired and my downloaded documents were cleared). Wanted to inspect binary with tools like Ilspy to get an idea.

Here's a new link: 

I can still reproduce it on a whim. However, there's one more thing that may play a role in that. The virtual machine where I test it is running under stock Hyper-V (no VirtualBox or VMware on top). It seems to use some kind of RDP access to show the screen of the machine internally. One of our customers who suffered from it also mentioned similar setup with virtual machine and RDP. It seems that after some update (*) I started getting incorrectly sized windows in this configuration where the DPI scaling is not applied.

(*) Not sure what update could cause it. The guest OS in the virtual machine is a snapshot of clean Windows 10 (1609) installation now. The program binaries were published earlier and didn't change. The only thing that I updated is the host OS but even that one is at 10.0.18363.836 which seems quite old by now. It also happens inside Windows 8.1 guest running in the same setup.

**Comment by filipnavara** [comment]
> Also, @filipnavara this PR may fix your issue but we still do not have the root cause for this. Can you share your binary one more time? (earlier link expired and my downloaded documents were cleared). Wanted to inspect binary with tools like Ilspy to get an idea.

Here's a new link: https://we.tl/t-XU3KCFjgau

I can still reproduce it on a whim. However, there's one more thing that may play a role in that. The virtual machine where I test it is running under stock Hyper-V (no VirtualBox or VMware on top). It seems to use some kind of RDP access to show the screen of the machine internally. One of our customers who suffered from it also mentioned similar setup with virtual machine and RDP. It seems that after some update (*) I started getting incorrectly sized windows in this configuration where the DPI scaling is not applied.

(*) Not sure what update could cause it. The guest OS in the virtual machine is a snapshot of clean Windows 10 (1609) installation now. The program binaries were published earlier and didn't change. The only thing that I updated is the host OS but even that one is at 10.0.18363.836 which seems quite old by now. It also happens inside Windows 8.1 guest running in the same setup.

**Comment by dreddy-work** [comment]
> > Also, @filipnavara this PR may fix your issue but we still do not have the root cause for this. Can you share your binary one more time? (earlier link expired and my downloaded documents were cleared). Wanted to inspect binary with tools like Ilspy to get an idea.
> 
> Here's a new link: https://we.tl/t-XU3KCFjgau
> 
> I can still reproduce it on a whim. However, there's one more thing that may play a role in that. The virtual machine where I test it is running under stock Hyper-V (no VirtualBox or VMware on top). It seems to use some kind of RDP access to show the screen of the machine internally. One of our customers who suffered from it also mentioned similar setup with virtual machine and RDP. It seems that after some update (*) I started getting incorrectly sized windows in this configuration where the DPI scaling is not applied.
> 
> (*) Not sure what update could cause it. The guest OS in the virtual machine is a snapshot of clean Windows 10 (1609) installation now. The program binaries were published earlier and didn't change. The only thing that I updated is the host OS but even that one is at 10.0.18363.836 which seems quite old by now. It also happens inside Windows 8.1 guest running in the same setup.

Thanks @filipnavara . I downloaded binary and saved.  Are you confirming that the same binary does not crash outside of the setup you described? From our last conversation, this version of the binary is crashing on a simple windows latest OS environment also. is that still true or is it only crashing in the environment setup you mentioned here. In either case, we will be taking this safe fix that should avoid the crash on the setup you  described. If we get any insights from binary for the root cause, we may be able to fix that too in .NET 5.0.

**Comment by RussKie** [comment]
Re-targeted to 5.0

File: src/Common/src/DpiHelper.DpiAwarenessContext.cs (hunk 1 above)
Comment (JeremyKuhne) [reply src/Common/src/DpiHelper.DpiAwarenessContext.cs]: Cleaning it up can be done in a separate PR/Issue. We should at least add a comment here.

Comment (RussKie) [reply src/Common/src/DpiHelper.DpiAwarenessContext.cs]: Added a comment. Please let me know if the wording is sufficiently clear.
