### PR TITLE
Add ScrollBar tests and fix a NRE

### LINKED ISSUE #1219: ScrollBar.OnMouseWheel(null) throws NRE
Should check for null before using

### PR DESCRIPTION
**Pull request by hughbe**
Fixes #1219

### CODE REVIEW

File: src/Common/tests/CommonTestHelper.cs [hunk 1]
```diff
@@ -296,6 +296,24 @@ public static TheoryData<Color> GetColorWithEmptyTheoryData()
             return data;
         }
 
+        public static TheoryData<Color, Color> GetBackColorTheoryData()
```
Comment (RussKie) [inline src/Common/tests/CommonTestHelper.cs]: I am really against any kind of sharing of input data between test fixtures (I support sharing within a fixture though) as it creates rigid coupling and makes tests brittle.
In my previous engagement I had spent 4 months untangling an incoherent mess of spaghetti test code and ultimately had to delete a lot of tests because there were simply non maintainable.

Please move these into fixtures that use them.

Comment (hughbe) [reply src/Common/tests/CommonTestHelper.cs]: I'm not sure about that. Mainly because these test fixtures are genuinely shared between other tests. For example, there are 21 controls that override `BackColor` like below and I would expect tests for that to use the `BackColor` fixture. Same goes for `ForeColor`
```
        public override Color BackColor
        {
            get
            {
                return base.BackColor;
            }
            set
            {
                base.BackColor = value;
            }
        }
```
